---
- command: dpkg-statoverride --force --update --add root sudo 4750 /bin/su
- name: apt
  apt: upgrade=full
- apt: pkg={{item}}
  with_items:
  - ntp
  - unattended-upgrades
  - htop
  - dstat
  - secure-delete
  - build-essential
  - git
- name: configure unattended upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic
#- name: disable default user accounts
#  command: chage -E 0 {{item}}
#  with_items:
#  - ubuntu
