---
- name: deny non-admin users access to su
  command: dpkg-statoverride --force --update --add root sudo 4750 /bin/su
- name: sudo NOPASSWD
  lineinfile: dest=/etc/sudoers.d/50-ubuntu create=yes regexp=^ubuntu line="ubuntu ALL=(ALL) NOPASSWD:ALL"
- name: remove password
  command: passwd ubuntu -d
- name: autologin
  file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755
- copy:
    src: etc_lightdm_lightdm.conf.d_50autologin.conf
    dest: /etc/lightdm/lightdm.conf.d/50autologin
    owner: root
    group: root
    mode: 644
- name: disable lock screen
  command: gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend 'false'
- name: disable sshd
  lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitRootLogin line="PermitRootLogin no"
- lineinfile: dest=/etc/ssh/sshd_config regexp=^RSAAuthentication line="RSAAuthentication no"
- lineinfile: dest=/etc/ssh/sshd_config regexp=^PubkeyAuthentication line="PubkeyAuthentication no"
- lineinfile: dest=/etc/ssh/sshd_config regexp=^PasswordAuthentication line="PasswordAuthentication no"
- name: apt
  apt: upgrade=full
- apt: pkg={{item}}
  with_items:
  - ntp
  - unattended-upgrades
  - htop
  - dstat
  - secure-delete
  - build-essential
- name: configure unattended upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic
