---
- name: deny non-admin users access to su
  command: dpkg-statoverride --force --update --add root sudo 4750 /bin/su
- name: sudo NOPASSWD
  lineinfile: dest=/etc/sudoers.d/50-ubuntu create=yes line="ubuntu ALL=(ALL) NOPASSWD:ALL"
- name: remove password
  command: passwd ubuntu -d
- name: autologin
  copy: src=etc_lightdm_lightdm.conf.d_50autologin.conf dest=/etc/lightdm/lightdm.conf.d/50autologin
- name: disable lock screen
  command: gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend 'false'
- name: apt
  apt: upgrade=full
- apt: pkg={{item}}
  with_items:
  - ntp
  - unattended-upgrades
  - htop
  - dstat
  - secure-delete
  - build-essential
  - ufw
- name: configure unattended upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic
- name: configure firewall
  lineinfile: dest=/etc/default/ufw create=yes line="IPV6=yes"
- name: configure firewall
  command: {{item}}
  with_items:
  - ufw reset
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw disable
  - ufw enable
